### ISSUE TITLE
Add savestates support

### ISSUE THREAD

**Issue by DavidAshta** [romhack/PsxVram-DotNet#1]
The New Look is amazing! Congratulation guys! i really love it too, but hey, how i use it? (sorry) i mean i thought i suppose to do the same thing, just extract the savestate zip and drop it inside PSXVram, but it doesn't let me do it, it keeps giving me an error about that inputfile 1mb, i really don't understand that

**Comment by romhack** [comment]
Thanks!
Savestates support isn't implemented yet - only raw binary dumps from debugging emulators like debug PCSX forks. Guess, it will not be too hard.
What emulator do you usually use?

**Comment by DavidAshta** [comment]
> Thanks!
> Savestates support isn't implemented yet - only raw binary dumps from debugging emulators like debug PCSX forks. Guess, it will not be too hard.
> What emulator do you usually use?

i use EPSXE to grab savestate files  ;D  and would be amazing if we could use Retroarch Savestate too, God, would be an awesome thing
(Thanks for change the title haha)

**Comment by romhack** [comment]
Added savestates support to  v.0.2, updated readme with additional features information.
Thank you! And let me know if you have any other feature ideas.
