### ISSUE TITLE
How can I "move" through the emulator code to edit it?

### ISSUE THREAD

**Issue by MiguLuz** [romhack/PsxVram-DotNet#2]
How can I "move" through the emulator code to edit it?

**Comment by MiguLuz** [comment]
I want to edit some palettes for the sprites but I don't know how

**Comment by romhack** [comment]
This tool is only for viewing VRAM. Palettes are stored in some way in different game's data files. You have to find code, which copies palettes to VRAM in debugging emulator and find where palette is stored.  
Each game can have it's own scheme of palettes storage.
