### ISSUE TITLE
 How to use?

### ISSUE THREAD

**Issue by MiguLuz** [romhack/PsxVram-DotNet#3]
https://tinypic.host/i/9NTig
Hello! I have some doubts and I wanted to know if you can help me
 I am modifying the memory with Cheat Engine, but I don't understand how to modify the texture palette, there are the offsets, could you explain to me how I should modify the palettes?

**Comment by romhack** [comment]
Hello, this tool is just for viewing video memory of PSX. If you want to modify actual game's textures, you will have to find it in game's resources in disk's ISO.
PsxVram-DotNet can help you: you can find scanline you're interested in and dump bytes, which form this scanline. Then you can try to search for this sequence of bytes in all game's files (ripped ISO folder).
If you're lucky and texture is not compressed, you will find exact .tim file or binary with this graphics in it. 
You can modify this file as you like and reassemble it back to ISO to get modified game's image.
