### ISSUE TITLE
Mac build?

### ISSUE THREAD

**Issue by Q-mii** [romhack/PsxVram-DotNet#4]
I'm playing a game on PCSX-Redux, but so far I need wine to run this app. It would really help to have a native mac build so I can save space. Would it be possible?

**Comment by romhack** [comment]
Currently this app is build on .net Framework, which means it's only for Windows. 
It's still possible to rewrite the code for .net MAUI or Xamarin mac, but I have no experience with that.
You could also check [this](https://github.com/romhack/PsxVram-SDL) repo - it's previous version, which was build on SDL library and theoretically could be build on Mac OS.
